"""Keyword dictionary mapping Italian keywords to category name_key values.

Each key is a lowercase keyword (or short phrase) that may appear inside a
transaction description.  The value is the ``name_key`` of the target category
from ``SYSTEM_CATEGORIES``.

Keywords are tried *longest-first* by the engine so that more-specific entries
(e.g. ``"amazon prime"`` → Abbonamenti) take precedence over shorter ones
(e.g. ``"amazon"`` → Elettronica).
"""
from __future__ import annotations

# Dict[str, str] — keyword (lowercase) → category name_key
KEYWORD_MAP: dict[str, str] = {
    # ── Alimentari > Supermercato ────────────────────────────────────────
    "esselunga": "Supermercato",
    "conad": "Supermercato",
    "coop": "Supermercato",
    "lidl": "Supermercato",
    "eurospin": "Supermercato",
    "carrefour": "Supermercato",
    "aldi": "Supermercato",
    "pam": "Supermercato",
    "despar": "Supermercato",
    "penny market": "Supermercato",
    "penny": "Supermercato",
    "md discount": "Supermercato",
    "iper": "Supermercato",
    "tigre": "Supermercato",
    "todis": "Supermercato",
    "simply": "Supermercato",
    "bennet": "Supermercato",
    "supermercato": "Supermercato",
    "ipercoop": "Supermercato",
    "famila": "Supermercato",
    # ── Alimentari > Ristorante ──────────────────────────────────────────
    "ristorante": "Ristorante",
    "pizzeria": "Ristorante",
    "trattoria": "Ristorante",
    "osteria": "Ristorante",
    "mcdonald": "Ristorante",
    "burger king": "Ristorante",
    "old wild west": "Ristorante",
    "roadhouse": "Ristorante",
    "autogrill": "Ristorante",
    "sushi": "Ristorante",
    "kebab": "Ristorante",
    # ── Alimentari > Bar/Caffè ───────────────────────────────────────────
    "bar ": "Bar/Caffè",
    "caffè": "Bar/Caffè",
    "starbucks": "Bar/Caffè",
    "pasticceria": "Bar/Caffè",
    "gelateria": "Bar/Caffè",
    # ── Alimentari > Delivery ────────────────────────────────────────────
    "deliveroo": "Delivery",
    "just eat": "Delivery",
    "justeat": "Delivery",
    "glovo": "Delivery",
    "uber eats": "Delivery",
    "foodora": "Delivery",
    # ── Casa > Affitto/Mutuo ─────────────────────────────────────────────
    "affitto": "Affitto/Mutuo",
    "mutuo": "Affitto/Mutuo",
    "canone locazione": "Affitto/Mutuo",
    # ── Casa > Utenze ────────────────────────────────────────────────────
    "enel": "Utenze",
    "eni gas": "Utenze",
    "a2a": "Utenze",
    "hera": "Utenze",
    "acea": "Utenze",
    "iren": "Utenze",
    "sorgenia": "Utenze",
    "edison": "Utenze",
    "italgas": "Utenze",
    "acquedotto": "Utenze",
    # ── Casa > Manutenzione ──────────────────────────────────────────────
    "ferramenta": "Manutenzione",
    "leroy merlin": "Manutenzione",
    "brico": "Manutenzione",
    "bricocenter": "Manutenzione",
    # ── Casa > Assicurazione casa ────────────────────────────────────────
    "assicurazione casa": "Assicurazione casa",
    "polizza casa": "Assicurazione casa",
    # ── Trasporti > Carburante ───────────────────────────────────────────
    "esso": "Carburante",
    "q8": "Carburante",
    "tamoil": "Carburante",
    "eni station": "Carburante",
    "total erg": "Carburante",
    "shell": "Carburante",
    "carburante": "Carburante",
    "benzina": "Carburante",
    "distributore": "Carburante",
    # ── Trasporti > Trasporto pubblico ───────────────────────────────────
    "trenitalia": "Trasporto pubblico",
    "italo": "Trasporto pubblico",
    "atm milano": "Trasporto pubblico",
    "atac": "Trasporto pubblico",
    "bus ": "Trasporto pubblico",
    "metro ": "Trasporto pubblico",
    "flixbus": "Trasporto pubblico",
    # ── Trasporti > Parcheggio ───────────────────────────────────────────
    "parcheggio": "Parcheggio",
    "sosta": "Parcheggio",
    "telepass": "Parcheggio",
    "mycicero": "Parcheggio",
    # ── Trasporti > Manutenzione auto ────────────────────────────────────
    "officina": "Manutenzione auto",
    "gommista": "Manutenzione auto",
    "autoricambi": "Manutenzione auto",
    "revisione": "Manutenzione auto",
    "carrozzeria": "Manutenzione auto",
    # ── Trasporti > Assicurazione auto ───────────────────────────────────
    "assicurazione auto": "Assicurazione auto",
    "rca": "Assicurazione auto",
    "polizza auto": "Assicurazione auto",
    # ── Salute > Farmacia ────────────────────────────────────────────────
    "farmacia": "Farmacia",
    "parafarmacia": "Farmacia",
    # ── Salute > Visite mediche ──────────────────────────────────────────
    "visita medica": "Visite mediche",
    "laboratorio analisi": "Visite mediche",
    "ecografia": "Visite mediche",
    "ospedale": "Visite mediche",
    "clinica": "Visite mediche",
    "radiologia": "Visite mediche",
    # ── Salute > Dentista ────────────────────────────────────────────────
    "dentista": "Dentista",
    "odontoiatrico": "Dentista",
    "studio dentistico": "Dentista",
    # ── Shopping > Abbigliamento ─────────────────────────────────────────
    "zara": "Abbigliamento",
    "h&m": "Abbigliamento",
    "decathlon": "Abbigliamento",
    "ovs": "Abbigliamento",
    "benetton": "Abbigliamento",
    "calzedonia": "Abbigliamento",
    "intimissimi": "Abbigliamento",
    "nike": "Abbigliamento",
    "adidas": "Abbigliamento",
    # ── Shopping > Elettronica ───────────────────────────────────────────
    "amazon": "Elettronica",
    "mediaworld": "Elettronica",
    "unieuro": "Elettronica",
    "apple": "Elettronica",
    "euronics": "Elettronica",
    "expert": "Elettronica",
    # ── Shopping > Casa e arredo ─────────────────────────────────────────
    "ikea": "Casa e arredo",
    "maisons du monde": "Casa e arredo",
    "mondo convenienza": "Casa e arredo",
    # ── Svago > Cinema/Teatro ────────────────────────────────────────────
    "cinema": "Cinema/Teatro",
    "teatro": "Cinema/Teatro",
    "uci cinema": "Cinema/Teatro",
    "the space": "Cinema/Teatro",
    # ── Svago > Sport ────────────────────────────────────────────────────
    "palestra": "Sport",
    "piscina": "Sport",
    "fitness": "Sport",
    # ── Svago > Viaggi ───────────────────────────────────────────────────
    "booking": "Viaggi",
    "ryanair": "Viaggi",
    "easyjet": "Viaggi",
    "airbnb": "Viaggi",
    "alitalia": "Viaggi",
    "ita airways": "Viaggi",
    "hotel": "Viaggi",
    "hostel": "Viaggi",
    "trivago": "Viaggi",
    "expedia": "Viaggi",
    "skyscanner": "Viaggi",
    "wizzair": "Viaggi",
    "vueling": "Viaggi",
    # ── Svago > Hobby ────────────────────────────────────────────────────
    "feltrinelli": "Hobby",
    "mondadori": "Hobby",
    # ── Servizi > Telefonia ──────────────────────────────────────────────
    "tim ": "Telefonia",
    "vodafone": "Telefonia",
    "wind tre": "Telefonia",
    "iliad": "Telefonia",
    "ho. mobile": "Telefonia",
    "postemobile": "Telefonia",
    "very mobile": "Telefonia",
    # ── Servizi > Internet ───────────────────────────────────────────────
    "fastweb": "Internet",
    "fibra": "Internet",
    # ── Servizi > Abbonamenti ────────────────────────────────────────────
    "netflix": "Abbonamenti",
    "spotify": "Abbonamenti",
    "disney+": "Abbonamenti",
    "amazon prime": "Abbonamenti",
    "dazn": "Abbonamenti",
    "youtube premium": "Abbonamenti",
    "youtube music": "Abbonamenti",
    "apple tv": "Abbonamenti",
    "now tv": "Abbonamenti",
    "sky": "Abbonamenti",
    "crunchyroll": "Abbonamenti",
    "twitch": "Abbonamenti",
    "tim vision": "Abbonamenti",
    "xbox game pass": "Abbonamenti",
    "playstation plus": "Abbonamenti",
    # ── Servizi > Software ───────────────────────────────────────────────
    "github": "Software",
    "google workspace": "Software",
    "microsoft 365": "Software",
    "adobe": "Software",
    "dropbox": "Software",
    "notion": "Software",
    "slack": "Software",
    "chatgpt": "Software",
    "openai": "Software",
    # ── Finanza > Commissioni bancarie ───────────────────────────────────
    "commissione": "Commissioni bancarie",
    "canone conto": "Commissioni bancarie",
    "bollo": "Commissioni bancarie",
    "spese tenuta": "Commissioni bancarie",
    "spese conto": "Commissioni bancarie",
    # ── Finanza > Tasse ──────────────────────────────────────────────────
    "imposta": "Tasse",
    "f24": "Tasse",
    "irpef": "Tasse",
    "imu": "Tasse",
    "tari": "Tasse",
    # ── Finanza > Consulenza ─────────────────────────────────────────────
    "commercialista": "Consulenza",
    "consulenza": "Consulenza",
    "notaio": "Consulenza",
    # ── Istruzione > Corsi ───────────────────────────────────────────────
    "corso": "Corsi",
    "udemy": "Corsi",
    "coursera": "Corsi",
    "formazione": "Corsi",
    # ── Istruzione > Libri ───────────────────────────────────────────────
    "libreria": "Libri",
    "libro": "Libri",
    # ── Istruzione > Materiale ───────────────────────────────────────────
    "cartoleria": "Materiale",
    "cancelleria": "Materiale",
    # ── Income ───────────────────────────────────────────────────────────
    "stipendio": "Stipendio",
    "retribuzione": "Stipendio",
    "salario": "Stipendio",
    "rimborso": "Rimborsi",
    "dividendo": "Dividendi",
    "dividendi": "Dividendi",
    "cedola": "Dividendi",
    "interessi creditori": "Interessi",
    "plusvalenza": "Plusvalenze",
    "freelance": "Freelance",
    "prestazione professionale": "Freelance",
    "fattura": "Freelance",
    "regalo": "Regali",
}
